steps:
# Build the Docker image 
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/cicd-demo', '-f', './src/main/docker/Dockerfile' '.']

# Push image to Google Container Registry (gcr)
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'push', 'gcr.io/$PROJECT_ID/cicd-demo']

# Deploy to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args: ['beta', 'run', 'deploy', 'cicd-demo', '--image', 'gcr.io/$PROJECT_ID/cicd-demo', '--allow-unauthenticated','--platform', 'managed', '--region', 'us-central1']

images:
- 'gcr.io/$PROJECT_ID/cicd-demo'
